FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY apps/web/package*.json ./apps/web/
RUN npm install

COPY . .

RUN npm run build --workspace=apps/web

FROM node:20-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/apps/web/dist ./dist

EXPOSE 5174

CMD ["serve", "-s", "dist", "-l", "5174"]